_target_: omg.motion.representation.G1MotionRepresentation
stats_path: assets/stats/g1_125d_stats.json
kinematics_path: assets/robots/g1/g1_kinematics.json
num_prev_states: 10
canonical_frame_idx: 9
feat_dim: 125
sequence_length: 60
rotation_representation: rot6d
