_target_: omg.generation.losses.motion.MotionLoss
simple_root_pos: 0.0
simple_root_rot: 0.0
simple_joint_dof: 0.0
simple_body_pos: 0.0
vel_root_pos: 0.0
vel_root_rot: 0.0
vel_joint_dof: 0.0
body_pos_consistency: 0.0
fk_body_pos: 0.0
fk_body_rot: 0.0
body_vel: 0.0
terrain_penetration: 0.0
contact_height: 0.0
contact_velocity: 0.0
seam_root_pos: 0.0
seam_root_rot: 0.0
seam_joint_dof: 0.0
seam_body_pos: 0.0
