_target_: omg.generation.losses.motion.MotionLoss
simple_root_pos: 1.0
simple_root_rot: 1.0
simple_joint_dof: 0.5
simple_body_pos: 0.5
body_pos_consistency: 1.0
vel_root_pos: 0.5
vel_root_rot: 0.02
vel_joint_dof: 0.01
fk_body_pos: 0.5
fk_body_rot: 0.1
body_vel: 0.03
terrain_penetration: 15.0
contact_height: 5.0
contact_velocity: 0.2
seam_root_pos: 1.0
seam_root_rot: 1.0
seam_joint_dof: 0.5
seam_body_pos: 0.5
contact_height_threshold: 0.03
contact_velocity_threshold: 0.5
